solarized:
  repo: https://github.com/seebi/tmux-colors-solarized.git
  path: lib
powerline:
  repo: https://github.com/erikw/tmux-powerline.git
  path: lib
wemux:
  repo: https://github.com/zolrath/wemux.git
  path: lib