#!/bin/bash

# Install program and dependencies, if doesn't yet exist.
[[ -z `command -v xclip` ]] && sudo apt-get install -y xclip
if [[ -z `command -v "tmux"` ]]; then
	sudo apt-get build-dep tmux
	cd /usr/local/src
	sudo git clone https://github.com/ThomasAdam/tmux.git
	cd tmux
	sudo ./autogen.sh && sudo ./configure && sudo make && sudo make clean install
fi

# Link configurations
ln -s $HOME/.tmux/.tmux.conf $HOME/.tmux.conf
ln -s $HOME/.tmux/.tmux-powerlinerc $HOME/.tmux-powerlinerc
cp $HOME/.tmux/lib/tmux-powerline/themes/default.sh $HOME/.tmux/lib/tmux-powerline/themes/elad.sh

# Install libraries
[[ -z `command -v tmuxinator` ]] && gem install tmuxinator --no-ri --no-rdoc

#WeMux
ln -s $HOME/.tmux/lib/wemux/wemux $HOME/.tmux/bin/wemux
sudo cp $HOME/.tmux/lib/wemux/wemux.conf.example /usr/local/etc/wemux.conf
sudo sed -i "s/change_this/$USER/g" /usr/local/etc/wemux.conf